### PR TITLE
rename "Open at master" => "Open at main"

### LINKED ISSUE #10: "Open in master" should be replaced with "open in main"
When I use this extension to grab a link I always have to manually replace the master part of the URL with main before sharing. It would be slightly more convenient if it did that automatically.

I'd be happy to contribute a fix for this, but I currently can't because of #9

### PR DESCRIPTION
**Pull request by ComputerDruid**
Technically I think this would break existing keyboard shortcuts if anyone has any set up, but It's not that hard to fix and I doubt anyone does.

Fixes #10

### CODE REVIEW

**Review by j-wing — APPROVED** [review]
LGTM. Thanks for the PR!

**Comment by ComputerDruid** [comment]
@j-wing can you release a new version of the plugin on the vscode marketplace? Let me know if there's anything I can do to help

**Comment by j-wing** [comment]
@ComputerDruid  Yes, thanks for the reminder! I tried a bit ago and ran into some local auth issues, will try to get those resolved this week.

**Comment by j-wing** [comment]
Hey @ComputerDruid  - I just published v1.5.0. VS code should auto-updated, but if you could give it a try and make sure your changes are working alright that would be great!

**Comment by ComputerDruid** [comment]
Yep, my work computer picked it up today and it seems to be working as expected. Thanks for making the release!

**Pull request merged**
